backend:
  name: github
  repo: yy0534105830-source/news
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "blog"
    label: "כתבות"
    folder: "content/blog"
    create: true
    fields:
      - { label: "כותרת", name: "title", widget: "string" }
      - { label: "קטגוריה", name: "category", widget: "select", options: ["חדשות", "ביטחוני", "חצרות קודש", "כלכלה", "פוליטי", "כללי"] }
      - { label: "כותרת משנה", name: "subtitle", widget: "string", required: false }
      - { label: "תמונה ראשית", name: "thumbnail", widget: "image", required: false }
      - { label: "תוכן הכתבה", name: "body", widget: "markdown" }

  - name: "flashes"
    label: "מבזקים"
    folder: "content/flashes"
    create: true
    fields:
      - { label: "תוכן המבזק", name: "title", widget: "string" }
